### ISSUE TITLE
Criação do pipeline hipsimage

### ISSUE THREAD

**Issue by crisingulani** [linea-it/hipsimage_gen#7]
```[tasklist]
### Tasks
- [x] Revisão dos bash scripts
- [ ] Criação de mecanismo para enviar parametros via yaml file
- [ ] Criação do workflow no Slurm para etapas de criação de bandas e consolidação
- [ ] Testes e documentação
```
